# Site Settings
title: Stokes Lab
email: markstokeslab@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://localhost:4444"
twitter_username: stokeslab
github_username:  stokeslab
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
